### ISSUE TITLE
Fails to filter after a specific URL is opened

### ISSUE THREAD

**Issue by nolar** [zalando-incubator/bro-q#1]
1. Install or re-install.
2. Open URL1: https://api.cryptonator.com/api/full/btc-usd?fa821dba_ipp_uid2=2KAqqXDHQc7imq5N%2fSKzHvpfLYX1dL%2fy7h5ScSQ%3d%3d&fa821dba_ipp_uid1=1521453593959&fa821dba_ipp_key=1521453647804%2Fo9mf6i0lMO%2fDtYRjy%2fakzA%3d%3d#broq-filter=.
3. It works.
4. Open URL2: ... (a protected url, reported privately)...
5. Get HTTP 401 or HTTP 200 — it does not matter what is the response, the effect is the same.
6. Reload URL1 — it does not work anymore for any URL.
7. Click "Reload" on the extension record in the settings.
8. Open URL1 again and see that it works again.

All other extensions were disabled during this experiment.

## Expected Behaviour

It works for all URLs.

## Current Behaviour

It does not.

## Steps to Reproduce (for bugs)

Seems like it reaches some failure state inside its background hidden tab for the second URL, regardless of the response structure (but maybe status).

## Your Environment

Mac OS X.
Chrome: Version 64.0.3282.186 (Official Build) (64-bit)
Extension version: 1.0.0
Installed from the archive, which was downloaded at https://github.com/zalando-incubator/bro-q/releases

**Comment by patandrick** [comment]
Hi nolar, 

unfortunately we can't reproduce this issue. 

I tried it with 3 different URLs:
1.  BTC-USD API
2.  internal API
3.  file from my computer

Can you maybe provide some additional informations that could help us to reproduce this issue ?

**Comment by patandrick** [comment]
Hi @nolar,

we found a solution and made a pull request.
I packed a release zip for you which you only have to unzip and load as extension.
