### ISSUE TITLE
Filtered JSON is sometimes empty when bro/q opens

### ISSUE THREAD

**Issue by harti2006** [zalando-incubator/bro-q#211]
## Expected Behaviour
When I open a plain application/json document with bro/q and no filter is applied in the url, the filtered json view should contain the full unfiltered document.

## Current Behaviour
Sometimes, usually when bro/q opens a document for the first time, the filtered json view just contains `{}` instead of the unfiltered document, even if no filter was applied. 

## Steps to Reproduce (for bugs)
Open an arbitrary application/json document or page

## Your Environment

* bro/q Version 1.4.0
* Chrome Version 71.0.3578.98
* Operating System and version (desktop or mobile): Desktop macOS Version 1.14.2

**Comment by patandrick** [comment]
Hi @harti2006,

how was the json data structured? 
For me this happens, when the json contains only an array []
then the output only shows {}

best regards;

**Comment by mrandi** [comment]
plz check with the new version 1.5.1 and reopen if needed.
