### ISSUE TITLE
Filter errors are not being shown

### ISSUE THREAD

**Issue by bbbco** [zalando-incubator/bro-q#281]
When an error to the filter occurs, it is not obvious what the issue might be. We should add a box that displays the resulting error message from JQ.

## Expected Behaviour

Add a box next to the filter input to display any error messages that might occur.

## Current Behaviour

No errors are being displayed

## Context

I'd like to know when my filter input is wrong and any helpful info on what needs fixed.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by mrandi** [comment]
great idea! thx for the contribution!
