### ISSUE TITLE
QUESTION: Chrome Extension Store Submission

### ISSUE THREAD

**Issue by raphaeleidus** [zalando-incubator/bro-q#87]
are there any plans to officially submit this extension to the chrome extension store?
And if not why?

I couldn't find any closed issues discussing this.

**Comment by mrandi** [comment]
@raphaeleidus actually nothing blocking us in doing so :) We just wanted to test it "internally" before releasing it in the store.
But I think I could work on this this week 👍

**Comment by mrandi** [comment]
Update: 
I'm having issue paying the 5$ dev fee, google is notified and hopefully they are going to fix it soon!
