### ISSUE TITLE
Discussion: Migrate UI Code to Library/Framework

### ISSUE THREAD

**Issue by raphaeleidus** [zalando-incubator/bro-q#91]
I did some poking around the codebase today to put together a pull request.
I found a couple things that I think could be improved. 
jQuery is included but barely used. Markup for the UI is hand made by calling `document.createElement`, then setting properties and then doing `appendChild` on other elements
This makes it pretty difficult to reason about the markup that is generated.

I would suggest either:

1. use jQuery much more heavily to allow you to write markup more naturally
2. remove jQuery entirely and add something like React, Vue, or Preact
3. use a full application framework like Knockout or Angular

Personally I lean towards option 2 and I would be happy to put together a PR to show what it would be like. 
I think option 1 would be minimal effort which is appealing.
I dont think option 3 is a good choice. The application will never scale to a point where there is a return on this sort of investment.

If jQuery can be removed and Preact gets added in it's place the resulting application would be much smaller overall as well which is nice. 

I would love to hear your thoughts.

**Comment by mrandi** [comment]
I'm completely with you!
I personally would also prefer to try option 2. I actually started looking into Vue, but is taking to much time for me :) 
I also have nothing against Preact, maybe React is too big for this project?

**Comment by raphaeleidus** [comment]
my primary reasoning for suggesting Preact is the sizing issue. It is much lighter 5kb (with preact-compat) vs React's 45kb (both gzipped).
Additionally it is a bit faster.

It is also API compatible with React so if we started with Preact and then ran into somewhere were we were like "I wish we had this react thing." It would be super easy to switch.

**Comment by raphaeleidus** [comment]
here is a sample of what it would look like: https://github.com/zalando-incubator/bro-q/pull/95/files
this has some bugs and I didn't fully wire up all the options into the editor because I was being lazy

**Comment by mrandi** [comment]
let's continue here https://github.com/zalando-incubator/bro-q/pull/167
