### ISSUE TITLE
When a filter is not provided, display only one editor

### ISSUE THREAD

**Issue by mrandi** [zalando-incubator/bro-q#93]
What do you think in displaying only one editor, to improve readability, when not filter is provided?

**Comment by harti2006** [comment]
Sounds useful. Alternatively I would suggest to have a button between both editors to switch between 3 modes:
- Full size left editor, right one collapsed
- Split 50/50
- Left editor collapsed, full size right editor

**Comment by anstit** [comment]
I think that could definitely improve readability and overview. I like hartis thoughts, I think the last option could be great to use in combination with the saved-filters!

**Comment by patandrick** [comment]
I already tried to implement it, but I doesn't feel so comfortable with css styling. Would be awesome if someone could provide this fullscreen left editor :)

**Comment by akread** [comment]
https://github.com/zalando-incubator/bro-q/pull/99

It is not exactly as described by @harti2006 but it is a good step one. It just allows you to hide the unfiltered json and exposes and option to do so by default when the extension loads for the first time on the page.
